# Generated by Django 4.2.1 on 2023-07-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0029_purchase_order_purchase_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='doc/purchase_order'),
        ),
    ]
