# Generated by Django 4.2.1 on 2023-07-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0030_alter_purchase_order_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order',
            name='adjustment',
        ),
    ]
