# Generated by Django 4.2.1 on 2023-07-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0031_remove_purchase_order_adjustment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_order',
            old_name='refer',
            new_name='ref',
        ),
    ]
