# Generated by Django 4.2.1 on 2023-07-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0032_rename_refer_purchase_order_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_order',
            old_name='Org_address',
            new_name='typ',
        ),
        migrations.RemoveField(
            model_name='purchase_order',
            name='Org_gst',
        ),
        migrations.RemoveField(
            model_name='purchase_order',
            name='Org_name',
        ),
    ]
