# Generated by Django 4.2.1 on 2023-07-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0035_purchase_order_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
