# Generated by Django 4.2.1 on 2023-07-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0036_purchase_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='status',
            field=models.CharField(default='Draft', max_length=255),
        ),
    ]
